// Auto-gerado por scripts/otimizar-capas.mjs — NÃO EDITAR MANUALMENTE.
// Mapeia ID do material → nome base do arquivo de capa (sem extensão).
// Arquivos vivem em public/logos/capas/optimized/{thumb,full,jpg}/<nome>.{webp,jpg}.

export const CAPAS_LOCAIS: Record<string, string> = {
  'amarelinha-em-miudos': 'amarelinhaeemmiudos',
  'kit-de-atividades-escola-e-lugar-de-pertencer': 'Auschwitzescolalugardepertencer',
  'caderno-metodologico-cidadania-e-democracia-desde-a-escola': 'cidadaniaedemocraciadesdeaescolacadernometodologico',
  'curso-ead-cidadania-e-politicas-publicas': 'cursoeadcidadaniaepoliticaspublicas',
  'direitos-e-cidadania-cadernos-do-professor': 'direitosecidadaniacadernosprofessoreletivaauschwitz',
  'roteiros-pedagogicos---caminhos-sustentaveis-acoes-locais-im': 'FundacaoFHC_caminhosustentaveis',
  'roteiros-pedagogicos---direitos-indigenas-em-foco': 'FundacaoFHC_direitosindigenas',
  'roteiros-pedagogicos---direitos-lgbtqiapn': 'FundacaoFHC_direitoslgbtqiapn',
  'roteiros-pedagogicos---direito-a-educacao': 'FundacaoFHC_direitoaeducacao',
  'colecao-coracoes-e-mentes---vol-4-educar-em-tempos-de-inteli': 'FundacaoFHC_educaremtemposdeIA',
  'colecao-coracoes-e-mentes---vol-2-ensino-religioso-e-valores': 'FundacaoFHC_ensinoreligoso',
  'infograficos': 'fundacaofhc_infograficoshistoriadedemocracia',
  'colecao-coracoes-e-mentes---vol-1-pensando-de-forma-autonoma': 'FundacaoFHC_internetedemocracia',
  'linhas-do-tempo': 'FundacaoFHC_linhasdotempo',
  'vale-a-pena-perguntar': 'FundacaoFHC_minidocumentarios',
  'roteiros-pedagogicos---mulheres-em-foco-caminhos-para-a-equi': 'FundacaoFHC_mulheresemfoco',
  'colecao-coracoes-e-mentes---vol-3-nacionalismo-e-democracia': 'FundacaoFHC_nacionalismo',
  'roteiros-pedagogicos---pessoas-com-deficiencia-em-foco': 'FundacaoFHC_pessoascomdeficiencia',
  'roteiros-pedagogicos---questoes-raciais-em-foco': 'FundacaoFHC_questoesraciaisemfoco',
  'roteiros-pedagogicos---saude-para-todos-enfrentando-desafios': 'FundacaoFHC_susnaescola',
  'roteiros-pedagogicos---transparencia-e-controle-social': 'FundacaoFHC_transparenciaecontrole',
  'chega-junto-juventudes': 'institutogilbertodimensteinjuventudes',
  'kit-de-atividades-democracia-e-bem-de-todos-nos': 'kitdeatividadesdemocraciaebemdetodosnos',
  'metodologia-7pegg': 'metodologiagentilezagenorisdade',
  'cidadania-democracia-e-participacao-praticas-pedagogicas-par': 'Mobis_Cidadaniademocraciaparticipacao',
  'sequencia-de-planos-de-aula': 'movimentofuturoplanodeaula',
  'biblioteca-educamidia-educacao-midiatica-e-temas-transversai': 'palavraabertaebiblitecaeducamidia',
  'kit-de-cartas-sociedade-conectada': 'palavraabertakitdecartassociedade2.0',
  'planos-de-aula-minha-voz-nas-redes-a-forca-das-hashtags-e-au': 'palavraabertaminhavoznasredes',
  'futuro-ancestral-na-escola': 'porvirfuturoancestralnaescola',
  'cartilha-violencia-contra-mulher-nao-e-normal': 'serenascartilhaparaprofissionais',
  'trilhas-formativas-online-sobre-prevencao-e-enfrentamento-de': 'serenastrilhasformativas',
  'guia-para-prevencao-as-violencias-contra-meninas-na-educacao': 'serenasviolenciaalagoas',
  'baralho-outras-historias-novas-identidades': 'vivenbaralhoeoutrashistorias',
  'cidade-em-jogo': 'vivencidademejogo',
  'sankofa-ananse-guia-de-letramento-racial-para-educadores': 'vivensankofaananse',
}
